#include "rudder.h"
void pid_rudder(int32 rcp, uint16 * rud, uint8 flag_tmp)//¶æ»úµ÷½Ú
{
  uint16 cen_rud = 775;
  rcp = -rcp;
  rcp = rcp * rcp * rcp;
  *rud = (uint16)(cen_rud + (float)(rcp * 0.0008));
 
    if(*rud > cen_rud+75)
    {
      *rud = cen_rud+75;
    }
    if(*rud < cen_rud-75)
    {
      *rud = cen_rud-75;
    }  
 
  
//  switch(rcp)
//  {
//  case   0:*rud = cen_rud + rcp;
//  break;
//  case   1:*rud = cen_rud + rcp;
//  break;	
//  case   2:*rud = cen_rud + rcp;
//  break;
//  case   3:*rud = cen_rud + rcp;
//  break;
//  case   4:*rud = cen_rud + rcp;
//  break;
//  case   5:*rud = cen_rud + rcp;
//  break;
//  case   6:*rud = cen_rud + rcp;
//  break;
//  case   7:*rud = cen_rud + rcp;
//  break;
//  case   8:*rud = cen_rud + rcp;
//  break;
//  case   9:*rud = cen_rud + rcp;
//  break;
//  case  10:*rud = cen_rud + rcp;
//  break;
//  case  11:*rud = cen_rud + rcp;
//  break;
//  case  12:*rud = cen_rud + rcp;
//  break;
//  case  13:*rud = cen_rud + rcp;
//  break;
//  case  14:*rud = cen_rud + rcp;
//  break;
//  case  15:*rud = cen_rud + rcp;
//  break;
//  case  16:*rud = cen_rud + rcp;
//  break;
//  case  17:*rud = cen_rud + rcp;
//  break;
//  case  18:*rud = cen_rud + rcp;
//  break;
//  case  19:*rud = cen_rud + rcp;
//  break;
//  case  20:*rud = cen_rud + rcp;
//  break;
//  case  21:*rud = cen_rud + rcp;
//  break;
//  case  22:*rud = cen_rud + rcp;
//  break;
//  case  23:*rud = cen_rud + rcp;
//  break;
//  case  24:*rud = cen_rud + rcp;
//  break;
//  case  25:*rud = cen_rud + rcp;
//  break;
//  case  26:*rud = cen_rud + rcp;
//  break;
//  case  27:*rud = cen_rud + rcp;
//  break;
//  case  28:*rud = cen_rud + rcp;
//  break;
//  case  29:*rud = cen_rud + rcp;
//  break;
//  case  30:*rud = cen_rud + rcp;
//  break;
//  case  31:*rud = cen_rud + rcp;
//  break;
//  case  32:*rud = cen_rud + rcp;
//  break;
//  case  33:*rud = cen_rud + rcp;
//  break;
//  case  34:*rud = cen_rud + rcp;
//  break;
//  case  35:*rud = cen_rud + rcp;
//  break;
//  case  36:*rud = cen_rud + rcp;
//  break;
//  case  37:*rud = cen_rud + rcp;
//  break;
//  case  38:*rud = cen_rud + rcp;
//  break;
//  case  39:*rud = cen_rud + rcp;
//  break;
//  case  40:*rud = cen_rud + rcp;
//  break;
//  case  41:*rud = cen_rud + rcp;
//  break;
//  case  42:*rud = cen_rud + rcp;
//  break;
//  case  43:*rud = cen_rud + rcp;
//  break;
//  case  44:*rud = cen_rud + rcp;
//  break;
//  case  45:*rud = cen_rud + rcp;
//  break;
//  case  46:*rud = cen_rud + rcp;
//  break;
//  case  47:*rud = cen_rud + rcp;
//  break;
//  case  48:*rud = cen_rud + rcp;
//  break;
//  case  49:*rud = cen_rud + rcp;
//  break;
//  case  50:*rud = cen_rud + rcp;
//  break;
//  case - 1:*rud = cen_rud + rcp;
//  break;
//  case - 2:*rud = cen_rud + rcp;
//  break;
//  case - 3:*rud = cen_rud + rcp;
//  break;
//  case - 4:*rud = cen_rud + rcp;
//  break;
//  case - 5:*rud = cen_rud + rcp;
//  break;
//  case - 6:*rud = cen_rud + rcp;
//  break;
//  case - 7:*rud = cen_rud + rcp;
//  break;
//  case - 8:*rud = cen_rud + rcp;
//  break;
//  case - 9:*rud = cen_rud + rcp;
//  break;
//  case -10:*rud = cen_rud + rcp;
//  break;
//  case -11:*rud = cen_rud + rcp;
//  break;
//  case -12:*rud = cen_rud + rcp;
//  break;
//  case -13:*rud = cen_rud + rcp;
//  break;
//  case -14:*rud = cen_rud + rcp;
//  break;
//  case -15:*rud = cen_rud + rcp;
//  break;
//  case -16:*rud = cen_rud + rcp;
//  break;
//  case -17:*rud = cen_rud + rcp;
//  break;
//  case -18:*rud = cen_rud + rcp;
//  break;
//  case -19:*rud = cen_rud + rcp;
//  break;
//  case -20:*rud = cen_rud + rcp;
//  break;
//  case -21:*rud = cen_rud + rcp;
//  break;
//  case -22:*rud = cen_rud + rcp;
//  break;
//  case -23:*rud = cen_rud + rcp;
//  break;
//  case -24:*rud = cen_rud + rcp;
//  break;
//  case -25:*rud = cen_rud + rcp;
//  break;
//  case -26:*rud = cen_rud + rcp;
//  break;
//  case -27:*rud = cen_rud + rcp;
//  break;
//  case -28:*rud = cen_rud + rcp;
//  break;
//  case -29:*rud = cen_rud + rcp;
//  break;
//  case -30:*rud = cen_rud + rcp;
//  break;
//  case -31:*rud = cen_rud + rcp;
//  break;
//  case -32:*rud = cen_rud + rcp;
//  break;
//  case -33:*rud = cen_rud + rcp;
//  break;
//  case -34:*rud = cen_rud + rcp;
//  break;
//  case -35:*rud = cen_rud + rcp;
//  break;
//  case -36:*rud = cen_rud + rcp;
//  break;
//  case -37:*rud = cen_rud + rcp;
//  break;
//  case -38:*rud = cen_rud + rcp;
//  break;
//  case -39:*rud = cen_rud + rcp;
//  break;
//  case -40:*rud = cen_rud + rcp;
//  break;
//  case -41:*rud = cen_rud + rcp;
//  break;
//  case -42:*rud = cen_rud + rcp;
//  break;
//  case -43:*rud = cen_rud + rcp;
//  break;
//  case -44:*rud = cen_rud + rcp;
//  break;
//  case -45:*rud = cen_rud + rcp;
//  break;
//  case -46:*rud = cen_rud + rcp;
//  break;
//  case -47:*rud = cen_rud + rcp;
//  break;
//  case -48:*rud = cen_rud + rcp;
//  break;
//  case -49:*rud = cen_rud + rcp;
//  break;
//  case -50:*rud = cen_rud + rcp;
//  break;  
//  }
}